//
// Created by david on 14/11/22.
//

#ifndef CPP_PROJET_2022_JEU_DIRECTIONTUILE_HPP
#define CPP_PROJET_2022_JEU_DIRECTIONTUILE_HPP

enum directionTuile {
    UP,DOWN,RIGHT,LEFT
};


#endif //CPP_PROJET_2022_JEU_DIRECTIONTUILE_HPP
