//
// Created by david on 13/11/22.
//

#ifndef CPP_PROJET_2022_JEU_ROLECARCASSONNE_HPP
#define CPP_PROJET_2022_JEU_ROLECARCASSONNE_HPP


enum class roleCarcassonne {
    VOLEUR,PAYSAN,MOINE,CHEVALIER,PARTISAN
};


#endif //CPP_PROJET_2022_JEU_ROLECARCASSONNE_HPP
