#ifndef CPP_PROJET_2022_JEU_COLORCARCASSONNE_HPP
#define CPP_PROJET_2022_JEU_COLORCARCASSONNE_HPP



enum colorCarcassonne {
    ROUGE,BLEU,VERT,JAUNE
};

#endif //CPP_PROJET_2022_JEU_COLORCARCASSONNE_HPP
