#ifndef CPP_PROJET_2022_JEU_ENVIRONMENT_CPP
#define CPP_PROJET_2022_JEU_ENVIRONMENT_CPP


enum class environment {
    ROUTE, VILLAGE, CHAMPS, ABAYES, INVALIDE
};


#endif //CPP_PROJET_2022_JEU_ENVIRONMENT_CPP
